name: runner1
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          cache: "pipenv"
      - name: Install pipenv
        run: pipx install pipenv
      - name: Install pipenv dependencies
        run: pipenv install
      - name: Run script
        with:
          python-version: "3.7"
          cache: "pipenv"
        env:
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        run: python main.py
